travis:
  secure:
    BINSTAR_TOKEN: Jq5Mxp5QDUi3U9JLlOzrpku8UcfOeh2oCscDCg2MTk0ICDMI8utLN9z06nZt0VBik0Ut/5Hag13Joi4ReXBF1/UCm4JhoWU7A0cdwNuKOC1++SPOuClKhrHCtQGnUvlImYqHoGhLDR6ZRcGjhumGhvwMo8jkwV0WB+KlKBXX539XtGiXzEY5jP2WpIcRLA6jQqgmOR+dMudu2ixPW2RlIBDHpShcWSHSxtjcbrKG32kMR9+5hnJK4wjiwGVvmUlKyyOBbo1+4lj9VNvdsuRH1MXrI3s2hcYbPcTytTTPYmb8pEd1ioDN3b+0s9MMVX+T9gzVRG9JKY1XYfDTTtqkLJ91WTf89fkxHKIiRHI0jXOWhNkH6IkAw1E58IdxUFexhfl4XQK9ewYcZhsJTiRi1NliPlWyxNx6H3aAGFg6cJIZK75YXBozVwBK1rKRPiQhGkHFwNOI/lulGIExF6BLvG4bEhkvAL0ZZvPjRh3xkZv5Le2srN42tfFFTGXePtI2nCEq2+SCSaI4pCvMXNBQs8PXoWfRdrMCs3MeMQuzARLXX7/pIJHP+WcrkM7R2t00cqTIDE9EC9cj+PD5M5YiTsXmB77XyDujAr71Wm5Qd8+YTrg5ZyCo/1hkUrKRJ4/UvrZa85hnNcJPQC1+RGm0asFI/BUDSoDmoa8rI+MtyqU=
conda_forge_output_validation: true
bot:
  automerge: true
